export const ROLES = {
  ADMIN: 'ADMIN',
  FINANCE: 'FINANCE',
  OPERATIONS: 'OPERATIONS'
};

export const OPERATIONAL_ROLES = [
  ROLES.ADMIN,
  ROLES.FINANCE,
  ROLES.OPERATIONS
];

export const FINANCE_VISIBLE_ROLES = [
  ROLES.ADMIN,
  ROLES.FINANCE
];
