export const ROLES = {
  ADMIN: 'ADMIN',
  CFO: 'CFO',
  PROCUREMENT_MANAGER: 'PROCUREMENT_MANAGER',
  WAREHOUSE: 'WAREHOUSE',
  PRODUCTION_MANAGER: 'PRODUCTION_MANAGER'
};

export const OPERATIONAL_ROLES = [
  ROLES.ADMIN,
  ROLES.CFO,
  ROLES.PROCUREMENT_MANAGER,
  ROLES.WAREHOUSE,
  ROLES.PRODUCTION_MANAGER
];

export const FINANCE_VISIBLE_ROLES = [
  ROLES.ADMIN,
  ROLES.CFO,
  ROLES.PROCUREMENT_MANAGER
];
